### ISSUE TITLE
Embeddining part is not running

### ISSUE THREAD

**Issue by abhi5485** [roomylee/rcnn-text-classification#9]
i have tried to run your code but embedding part is not running. Its giving me various errors such as "vocab_size is not defined", "word_embedding_size is not defined" and "self is not defined". Please tell me how to get rid of these problems.

**Comment by roomylee** [comment]
@abhi5485 
Hi, I'm sorry for late.
I can not understand the situation you are in. There are no problems when i run.
Please tell me your problems more details.

**Comment by abhi5485** [comment]
When I try to run your code I get the following error: 

$python train.py
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    FLAGS._parse_flags()
  File "/home/user/.local/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 85, in __getattr__
    return wrapped.__getattr__(name)
  File "/home/user/.local/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 472, in __getattr__
    raise AttributeError(name)
AttributeError: _parse_flags

Can you give a step by step guide on how to run?

**Comment by jyaken** [comment]
Had the same issue. Solved by replace 
FLAGS._parse_flags() with
import sys
FLAGS(sys.argv)
